services:

 elasticsearch:
  image: elasticsearch:tran
  container_name: elasticsearch
  build:
   context: elasticsearch
   dockerfile: Dockerfile
  ports:
   - "9200:9200"
  volumes: 
   - els_data:/usr/share/elasticsearch/data
   - certs:/usr/share/elasticsearch/config/certs
  environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.password=${ELASTIC_PASSWORD}
  depends_on:
    setup:
      condition: service_healthy
  healthcheck:
    test: ["CMD-SHELL", "curl -u elastic:${ELASTIC_PASSWORD} -s --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt https://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
    interval: 5s
    timeout: 10s
    retries: 5

 setup:
  image: setup:tran
  container_name: setup
  build:
    context: setup
    dockerfile: Dockerfile
  environment:
    - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    - LOGSTASH_PASSWORD=${LOGSTASH_PASSWORD}
  volumes:
    - certs:/usr/share/elasticsearch/config/certs
    - ./setup/utils/instances.yml:/usr/share/elasticsearch/config/instances.yml
    - ./setup/dashboard.ndjson:/usr/share/kibana/dashboard.ndjson
  healthcheck:
    test: ["CMD", "test", "-f", "/tmp/certs_ready"]
    interval: 3s
    retries: 7
    start_period: 2s
    timeout: 3s

 logstash:
  image: logstash:tran
  container_name: logstash
  build:
   context: logstash
   dockerfile: Dockerfile
  ports:
   - "5044:5044"
   - "5000:5000"
  depends_on:
    setup:
      condition: service_healthy
  volumes:
    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./logstash/pipeline:/usr/share/logstash/pipeline
    - certs:/usr/share/logstash/config/certs
  environment:
    - LOGSTASH_PASSWORD=$LOGSTASH_PASSWORD

 kibana:
  image: kibana:tran
  build:
   context: kibana
   dockerfile: Dockerfile
  container_name: kibana
  depends_on:
    setup:
      condition: service_healthy
  environment:
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
  volumes:
    - certs:/usr/share/kibana/config/certs
  ports:
   - "5601:5601"

 backend:
  image: backend
  container_name: backend
  build:
    context: backend
    dockerfile: Dockerfile
  ports:
    - "3000:3000"
  volumes:
    - ./backend/src:/app/src
  
  
  
volumes:
 els_data:
 certs:
